Authentication (without database)
Frontend-Cafe/healthy-dev-backend pull request #2
Opened 2020-01-18 23:22 UTC by Santiago-j-s

2020-01-19 02:31 UTC, ldelelis requested changes
:tada: Muy buena la implementacion del JWT!

Dejo un par de comentarios a revisar, cc @Santiago-j-s

2020-01-19 02:31 UTC, ldelelis commented on src/app.controller.ts
> +import { Controller, Request, Post, Get, UseGuards } from '@nestjs/common';
Esto no deberia ir como un controller del modulo auth?

2020-01-19 02:31 UTC, ldelelis commented on src/auth/auth.service.ts
> +    if (user && user.password === pass) {
Aca me hace ruido que estemos comparando contra una contrase;a en texto plano... No se esta encriptando el password cuando se guarda?

2020-01-19 02:31 UTC, ldelelis commented on src/auth/constants.ts
> +  secret: 'secretKey',
No es critico, pero aca se podria hacer que cargue el valor desde una variable de entorno: https://12factor.net/es/config

2020-01-19 02:31 UTC, ldelelis commented on src/auth/local.strategy.ts
> +    const user = await this.authService.validateUser(username, password);
Como el resultado de `validateUser` es una confirmacion de si es correcto o no, estaria bueno para la legibilidad que la variable refleje esto. Es decir, en vez de ser llamada `user` por tener que ver con usuarios, se podria pensar algo como `is_valid`, para dar a entender la intencion de la funcion

2020-01-19 02:31 UTC, ldelelis commented on src/users/users.service.ts
> +        this.users = [
nit: estaria bueno dejar comentado que esto es temporal hasta tener una base de datos. Para no llevarse sorpresas en el futuro :sweat_smile:

2020-01-19 06:57 UTC, FDSoftware commented on src/auth/auth.service.ts
> +    if (user && user.password === pass) {
Tengo entendido que algunos en win tienen problemas con bcrypt porque tienen que compilarlo y había un quilombo raro, capaz que para *parchear* provisoriamente hasta que arreglen el tema van a usar eso

2020-01-19 07:00 UTC, franmper commented on src/auth/auth.service.ts
> +    if (user && user.password === pass) {
Esto de todas maneras con Santiago habíamos hablado de hacerlo tal cual la documentación de Nest, solo para ir aclimantandonos y después si ver de hacer algo más seguro, junto con la conexión con el front. Lo de bcrypt era que necesitaba Python y tiraba error eso. Pero solo se borró para poder montar docker y quedó ahí.

2020-01-19 07:03 UTC, FDSoftware requested changes
básicamente, revisen lo que menciono @ldelelis , fuera de eso, esta bien el código

2020-01-19 16:08 UTC, FDSoftware commented on src/auth/auth.service.ts
> +    if (user && user.password === pass) {
en docker jodía bcrypt? cosa rara

2020-01-19 18:30 UTC, ldelelis commented on src/auth/auth.service.ts
> +    if (user && user.password === pass) {
@FDSoftware no era que jodia en docker, sino que la imagen se armo sin esa consideracion. El problema segun entiendo era mas sobre los entornos locales

2020-01-20 23:33 UTC, franmper commented on src/auth/local.strategy.ts
> +    const user = await this.authService.validateUser(username, password);
Le agregue el `is_valid_user`. Para que también haga referencia a que la validación es del usuario.

2020-01-21 00:31 UTC, franmper commented on src/auth/constants.ts
> +  secret: 'secretKey',
Hice el commit, esto pueden revisar que este bien?

2020-04-20 17:47 UTC, Raagh commented on src/auth/auth.service.ts
> +    const is_valid_user = await this.usersService.findOne(username);
es una boludez pero mejor creo que agarrarlo antes de que se descontrole, camelCase en vez de snake_case

2020-04-20 17:50 UTC, Raagh commented on src/auth/auth.controller.ts
> +    @Post('auth/login')
las api's tienen que estar versionadas. definir un path global de v1/

2020-07-18 17:03 UTC, closed without merging